package com.reed.leif

const val REQUEST_IMAGE_CAPTURE = 1
const val REQUEST_LOCATION_ACCESS = 2
const val REQUEST_CAMERA_ACCESS = 3
const val SESSION_ID = "SESSION_ID"
const val LOCATION_UPDATE = "LOCATION_UPDATE"
const val LOCATION_UPDATE_BACKLOG = "LOCATION_UPDATE_BACKLOG"
const val LOCATION_UPDATE_DATA = "LOCATION_UPDATE_DATA"
const val LOCATION_NOTIFICATION_ID = 1
const val LOCATION_NOTIFICATION_CHANNEL_ID = "channel_01"
const val TAG = "[Leif]"
